#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import platform
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Iterable

COMMON_BROWSERS = [
    "arc",
    "brave",
    "chrome",
    "chromium",
    "edge",
    "firefox",
    "librewolf",
    "opera",
    "opera_gx",
    "vivaldi",
    "zen",
]


def eprint(message: str) -> None:
    print(message, file=sys.stderr)


def try_load_rookiepy():
    try:
        import rookiepy  # type: ignore
    except ModuleNotFoundError:
        return None
    return rookiepy


def load_rookiepy():
    rookiepy = try_load_rookiepy()
    if rookiepy is None:
        eprint("rookiepy is not installed. Install it with: pip3 install -U rookiepy")
        raise SystemExit(2)
    return rookiepy


def normalize_browser_name(name: str) -> str:
    return name.strip().lower().replace("-", "_")


def split_domains(raw_domains: Iterable[str] | None) -> list[str] | None:
    if not raw_domains:
        return None

    domains: list[str] = []
    for item in raw_domains:
        for part in item.split(","):
            value = part.strip()
            if value:
                domains.append(value)
    return domains or None


def platform_browsers() -> list[str]:
    names = list(COMMON_BROWSERS)
    if platform.system() == "Darwin":
        names.append("safari")
    if platform.system() == "Windows":
        names.extend(["internet_explorer", "octo_browser"])
    return sorted(names)


def available_browsers(rookiepy=None) -> list[str]:
    names = platform_browsers()
    if rookiepy is None:
        return names
    return sorted(name for name in names if hasattr(rookiepy, name))


def get_browser_loader(rookiepy, browser_name: str):
    normalized = normalize_browser_name(browser_name)
    if not hasattr(rookiepy, normalized):
        supported = ", ".join(available_browsers(rookiepy))
        raise SystemExit(
            f"Unsupported browser '{browser_name}'. Supported values: {supported}"
        )
    return getattr(rookiepy, normalized)


def load_cookies(args):
    if args.path and args.browser:
        raise SystemExit("Use either --browser or --path, not both.")

    rookiepy = load_rookiepy()
    domains = split_domains(args.domain)

    if args.path:
        return rookiepy.any_browser(
            db_path=str(Path(args.path).expanduser()),
            domains=domains,
            key_path=str(Path(args.key_path).expanduser()) if args.key_path else None,
        )

    if args.browser:
        browser_fn = get_browser_loader(rookiepy, args.browser)
        return browser_fn(domains)

    return rookiepy.load(domains)


def cookie_header(cookies: list[dict]) -> str:
    pairs = []
    for cookie in cookies:
        name = cookie.get("name")
        value = cookie.get("value")
        if name and value is not None:
            pairs.append(f"{name}={value}")
    return "; ".join(pairs)


def cookie_netscape(rookiepy, cookies: list[dict]) -> str:
    if hasattr(rookiepy, "to_netscape"):
        return rookiepy.to_netscape(cookies)

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by rookie_tool.py",
        "",
    ]
    for cookie in cookies:
        domain = cookie["domain"]
        if cookie.get("http_only"):
            domain = f"#HttpOnly_{domain}"
        lines.append(
            "\t".join(
                [
                    domain,
                    str(cookie["domain"].startswith(".")).upper(),
                    cookie["path"],
                    str(cookie["secure"]).upper(),
                    str(cookie.get("expires") or 0),
                    cookie["name"],
                    str(cookie.get("value") or ""),
                ]
            )
        )
    return "\n".join(lines) + "\n"


def format_cookies(output_format: str, cookies: list[dict]) -> str:
    rookiepy = load_rookiepy()
    if output_format == "json":
        return json.dumps(cookies, indent=2)
    if output_format == "header":
        return cookie_header(cookies)
    if output_format == "netscape":
        return cookie_netscape(rookiepy, cookies)
    raise SystemExit(f"Unsupported format: {output_format}")


def write_output(output_path: str | None, data: str) -> None:
    if output_path:
        path = Path(output_path).expanduser()
        path.write_text(data, encoding="utf-8")
        print(str(path))
        return
    print(data)


def command_doctor(_args) -> int:
    print(f"python: {sys.version.split()[0]}")
    print(f"platform: {platform.platform()}")
    try:
        rookiepy = load_rookiepy()
    except SystemExit:
        print("rookiepy: missing")
        print("browsers:")
        for name in available_browsers():
            print(f"- {name.replace('_', '-')}")
        return 2

    version_fn = getattr(rookiepy, "version", None)
    version = version_fn() if callable(version_fn) else "unknown"
    print(f"rookiepy: {version}")
    print("browsers:")
    for name in available_browsers(rookiepy):
        print(f"- {name.replace('_', '-')}")
    return 0


def command_list(_args) -> int:
    rookiepy = try_load_rookiepy()

    for name in available_browsers(rookiepy):
        print(name.replace("_", "-"))
    return 0


def command_extract(args) -> int:
    cookies = load_cookies(args)
    data = format_cookies(args.format, cookies)
    write_output(args.output, data)
    return 0


def command_request(args) -> int:
    rookiepy = load_rookiepy()
    cookies = load_cookies(args)
    jar = rookiepy.to_cookiejar(cookies)

    headers = {}
    for raw_header in args.header or []:
        if ":" not in raw_header:
            raise SystemExit(
                f"Invalid header '{raw_header}'. Use the form 'Name: Value'."
            )
        name, value = raw_header.split(":", 1)
        headers[name.strip()] = value.strip()

    data = args.data.encode("utf-8") if args.data is not None else None
    request = urllib.request.Request(
        args.url,
        data=data,
        headers=headers,
        method=args.method.upper(),
    )
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))

    try:
        with opener.open(request, timeout=args.timeout) as response:
            body = response.read().decode("utf-8", errors="replace")
            if args.include_headers:
                eprint(f"status: {response.status}")
                for key, value in response.headers.items():
                    eprint(f"{key}: {value}")
            write_output(args.output, body)
            return 0
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        if args.include_headers:
            eprint(f"status: {exc.code}")
            for key, value in exc.headers.items():
                eprint(f"{key}: {value}")
        write_output(args.output, body)
        return 1


def add_source_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--browser", help="Browser loader name, for example chrome")
    parser.add_argument("--path", help="Custom cookies database path")
    parser.add_argument(
        "--key-path",
        help="Optional custom key path such as Chromium Local State",
    )
    parser.add_argument(
        "--domain",
        action="append",
        help="Domain filter. Repeat the flag or pass a comma-separated list.",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Utilities for browser-cookie extraction with rookiepy."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor_parser = subparsers.add_parser("doctor", help="Check environment")
    doctor_parser.set_defaults(func=command_doctor)

    list_parser = subparsers.add_parser("list", help="List supported browsers")
    list_parser.set_defaults(func=command_list)

    extract_parser = subparsers.add_parser(
        "extract", help="Extract cookies as JSON, Netscape, or header string"
    )
    add_source_arguments(extract_parser)
    extract_parser.add_argument(
        "--format",
        choices=["json", "netscape", "header"],
        default="json",
        help="Output format",
    )
    extract_parser.add_argument("--output", help="Write output to this file")
    extract_parser.set_defaults(func=command_extract)

    request_parser = subparsers.add_parser(
        "request", help="Send an HTTP request with cookies loaded from the browser"
    )
    add_source_arguments(request_parser)
    request_parser.add_argument("--url", required=True, help="Target URL")
    request_parser.add_argument(
        "--method", default="GET", help="HTTP method, default: GET"
    )
    request_parser.add_argument(
        "--header",
        action="append",
        help="Extra header in the form 'Name: Value'",
    )
    request_parser.add_argument("--data", help="Request body for POST/PUT/PATCH")
    request_parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="Request timeout in seconds",
    )
    request_parser.add_argument(
        "--include-headers",
        action="store_true",
        help="Print response status and headers to stderr",
    )
    request_parser.add_argument("--output", help="Write response body to this file")
    request_parser.set_defaults(func=command_request)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
