---
last_mapped: REPLACE_TIMESTAMP
total_files: REPLACE_COUNT
analysis_method: GitNexus knowledge graph + Oracle documentation
confidence: REPLACE_LEVEL
generated_docs:
  - CODEBASE_MAP.md
gitnexus_analysis: REPLACE_YES_OR_NO
---

# Codebase Map

> Auto-generated by Codebase Oracle. Last mapped: REPLACE_TIMESTAMP
> Analysis method: GitNexus knowledge graph + Oracle documentation

<!-- ORACLE:OVERVIEW
Lead fills this section.

Data sources:
1. GitNexus knowledge graph for project-level nodes, edges, clusters, flows
2. Use overview.md.tpl template structure for project overview
3. Summarize in 2-3 sentences: what the system is, what it does, who it's for
-->

## System Overview

REPLACE: 2-3 sentence summary

**Stack**: REPLACE: key technologies
**Architecture**: REPLACE: pattern name

## Source Documentation

<!-- ORACLE:SOURCES
List the documentation sources used.

GitNexus knowledge graph provides:
- Nodes: functions, classes, methods with file:line locations
- Edges: imports, calls, inheritance, type usage
- Clusters: functional communities with cohesion scores
- Flows: execution paths from entry points
- Hybrid search: BM25 + semantic across the graph

```bash
# Check GitNexus analysis
npx gitnexus analyze

# List Oracle-written module docs
ls docs/*.md | grep -v CODEBASE_MAP | grep -v c4 | grep -v key-flows | grep -v dependency
```
-->

**GitNexus Analysis**: REPLACE_YES_OR_NO

| Source | Description |
|--------|-------------|
| GitNexus graph | Nodes, edges, clusters, flows, hybrid search |
| [graph.html](graph.html) | Interactive dependency viewer |
| REPLACE | REPLACE: list Oracle-written module .md files |

## Graph Metrics

<!-- ORACLE:METRICS
From GitNexus knowledge graph:
- Count nodes (functions, classes, methods)
- Count edges (imports, calls, inheritance)
- Count clusters (functional communities)
-->

| Metric | Count |
|--------|-------|
| Nodes (functions/classes) | REPLACE |
| Edges (imports/calls) | REPLACE |
| Clusters/Modules | REPLACE |
| Files Analyzed | REPLACE |

## Architecture Docs

<!-- ORACLE:DOC_INDEX
Only include rows for docs that were actually generated.
-->

### Oracle-Written Analysis

| Document | Description |
|----------|-------------|
| [Architecture](architecture.md) | System context, C4 diagrams, design decisions |
| [Dependencies](dependencies.md) | Dependency graph, hub analysis, blast radius |
| [Key Flows](key-flows.md) | Cross-module execution paths |
| [API Surface](api-surface.md) | Public interfaces and endpoints |
| [Data Model](data-model.md) | Data structures and schemas |
| [Infrastructure](infrastructure.md) | Deployment and infrastructure |
| [Product Requirements](product-requirements.md) | Inferred product requirements |

### Oracle-Written Module Docs

<!-- ORACLE:MODULE_DOCS
List Oracle-written module docs:
```bash
ls docs/*.md | grep -v CODEBASE_MAP | grep -v c4 | grep -v key-flows | grep -v dependency
```
-->

| Document | Description |
|----------|-------------|
| REPLACE | REPLACE: module .md files |

## Hub Files

<!-- ORACLE:HUBS
From GitNexus knowledge graph:
- Query nodes with highest fan-in (most dependents)
- These are architectural linchpins — change carefully
-->

| Package | Dependents | Stability | Risk |
|---------|-----------|-----------|------|
| REPLACE | REPLACE | REPLACE | REPLACE |

## Module Guide

<!-- ORACLE:MODULES
From GitNexus clusters and Oracle-written module docs.
Each cluster represents a functional community of related code.
-->

### REPLACE: Module Name

**Purpose**: REPLACE
**Layer**: REPLACE
**Detailed docs**: [{module}.md]({module}.md)

| Directory | Purpose | Layer |
|-----------|---------|-------|
| REPLACE | REPLACE | REPLACE |

## Confidence Assessment

Overall: REPLACE_BAR REPLACE_PERCENTAGE%

**High confidence:**
- REPLACE — REPLACE_REASON

**Lower confidence:**
- REPLACE — REPLACE_REASON

## Caveats

<!-- ORACLE:CAVEATS
If confidence < 5, list assumptions and gaps.
-->

REPLACE: assumptions and gaps (delete if confidence = 5)
